spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/mydb
        username: user
        password: password
        driver-class-name: org.postgresql.Driver
        hikari:
            maximum-pool-size: 10
            minimum-idle: 5
            idle-timeout: 30000
            max-lifetime: 1800000

    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format_sql: true

